import cookieParser from 'cookie-parser';
import cors from 'cors';
import express from 'express';
import { createSellerRouter } from './seller/routes/seller.routes.js';
import { createReturnRouter } from './returns/return.routes.js';
import { createAdminRouter } from './admin/routes/admin.routes.js';
import { createAdminStoreController } from './admin/controllers/admin-store.controller.js';
import { createAdminStoreService } from './admin/services/admin-store.service.js';
import { createAdminReturnController } from './admin/controllers/admin-return.controller.js';
import { createAdminReturnService } from './admin/services/admin-return.service.js';
import { createAdminReturnRepository } from './admin/repositories/admin-return.repository.js';
import { createStoreRouter } from './seller/routes/store.routes.js';
import { createStoreController } from './seller/controllers/store.controller.js';
import { createStoreService } from './seller/services/store.service.js';
import { createProductController } from './seller/controllers/product.controller.js';
import { createProductService } from './seller/services/product.service.js';
import { createProductRepository } from './seller/repositories/product.repository.js';
import { createStoreRepository } from './seller/repositories/store.repository.js';
import { createProfileRouter } from './user/routes/profile.routes.js';
import { createProfileService } from './user/services/profile.service.js';
import { createOrderController } from './user/controllers/order.controller.js';
import { createOrderRepository } from './user/repositories/order.repository.js';
import { createOrderService } from './user/services/order.service.js';
import { createReorderService } from './user/services/reorder.service.js';
import { createOrderRouter } from './user/routes/order.routes.js';
import { createAddressController } from './user/controllers/address.controller.js';
import { createAddressRepository } from './user/repositories/address.repository.js';
import { createAddressService } from './user/services/address.service.js';
import { createAddressRouter } from './user/routes/address.routes.js';
import { createCatalogRouter } from './user/routes/catalog.routes.js';
import { createCatalogController } from './user/controllers/catalog.controller.js';
import { createCatalogService } from './user/services/catalog.service.js';
import { createCatalogRepository } from './user/repositories/catalog.repository.js';
import { createSellerOrderController } from './seller/controllers/seller-order.controller.js';
import { createSellerOrderService } from './seller/services/seller-order.service.js';
import { createSellerOrderRepository } from './seller/repositories/seller-order.repository.js';

import { env } from './config/env.js';
import { createAuthController } from './shared/controllers/auth.controller.js';
import { createCartController } from './user/controllers/cart.controller.js';
import { createFavoriteController } from './user/controllers/favorite.controller.js';
import { errorMiddleware } from './middlewares/error.middleware.js';
import { requestLogger } from './middlewares/request-logger.middleware.js';
import { createOtpRepository } from './shared/repositories/otp.repository.js';
import { createCartRepository } from './user/repositories/cart.repository.js';
import { createFavoriteRepository } from './user/repositories/favorite.repository.js';
import { createUserRepository } from './shared/repositories/user.repository.js';
import { createAuthRouter } from './shared/routes/auth.routes.js';
import { createCartRouter } from './user/routes/cart.routes.js';
import { createFavoriteRouter } from './user/routes/favorite.routes.js';
import { createAuthService } from './shared/services/auth.service.js';
import { createCartService } from './user/services/cart.service.js';
import { createFavoriteService } from './user/services/favorite.service.js';

export function createApp() {
  const app = express();
  const orderRepository = createOrderRepository();
  const catalogRepository = createCatalogRepository();
  const authService = createAuthService(createUserRepository(), createOtpRepository());
  const authController = createAuthController(authService);
  const storeService = createStoreService(createStoreRepository());
  const storeController = createStoreController(storeService);
  const adminStoreController = createAdminStoreController(createAdminStoreService());
  const adminReturnController = createAdminReturnController(createAdminReturnService(createAdminReturnRepository()));
  const cartService = createCartService(createCartRepository(), catalogRepository);
  const cartController = createCartController(cartService);
  const favoriteService = createFavoriteService(createFavoriteRepository());
  const favoriteController = createFavoriteController(favoriteService);

  app.use(cors({ origin: env.CLIENT_ORIGIN === '*' ? true : env.CLIENT_ORIGIN, credentials: true }));
  app.use(cookieParser());
  app.use(requestLogger);
  app.use('/api/v1/stores', createStoreRouter(storeController));
  app.use('/api/v1/seller', createSellerRouter(storeController,
    createProductController(createProductService(createProductRepository())),
    createSellerOrderController(createSellerOrderService(createSellerOrderRepository()))));
  app.use(express.json({ limit: '1mb' }));
  app.use('/api/v1/returns', createReturnRouter(catalogRepository));
  app.use('/api/v1/admin', createAdminRouter(adminStoreController, adminReturnController));
  app.get('/health', (_request, response) => response.status(200).json({ status: 'ok' }));
  app.use('/api/v1/products', createCatalogRouter(createCatalogController(createCatalogService(catalogRepository))));
  app.use('/api/v1/auth', createAuthRouter(authController));
  app.use('/api/v1/profile', createProfileRouter(createProfileService(createUserRepository())));
  app.use('/api/v1/cart', createCartRouter(cartController));
  app.use('/api/v1/orders', createOrderRouter(createOrderController(createOrderService(orderRepository, env.DELIVERY_CHARGE, catalogRepository), createReorderService(orderRepository, catalogRepository))));
  app.use('/api/v1/addresses', createAddressRouter(createAddressController(createAddressService(createAddressRepository()))));
  app.use('/api/v1/favorites', createFavoriteRouter(favoriteController));
  app.use(errorMiddleware);
  return app;
}
